apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: lixd-readpod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readpod
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: lixd
