apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: myapp
      release: tom
  template:
    metadata:
      name: myapp-pod
      labels: 
        app: myapp
        release: tom
        environment: qa
    spec:      
      containers:
      - name: myapp-container
        image: nginx:1.17.4-alpine
        ports: 
        - name: http
          containerPort: 80
    
