apiVersion: v1
kind: Pod
metadata:
    name: busybox
    namespace: default
    labels: 
        app: busybox
spec:
    imagePullSecrets:
      - name: harbor
    containers:
    - name: busybox
      image: 10.20.16.83/k8s/busybox
      command: 
      - ping
      - 114.114.114.114
