apiVersion: v1
kind: Pod
metadata:
    name: pod-temp
    namespace: default
    labels: 
        app: myapp
spec:
    containers:
    - name: myapp
      image: busybox
      imagePullPolicy: IfNotPresent
      ports:
      - name: http
        containerPort: 80
      volumeMounts:
      - name: html
        mountPath: /data/web/html/ 
      command: ["/bin/sh","-c","httpd -f -h /data/web/html/"]
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: html
        mountPath: /data/
      command: ["/bin/sh","-c","while true;do uptime >>/data/index.html;sleep 5;done"]
    volumes:
    - name: html
      emptyDir: {}   
