apiVersion: v1
kind: Pod
metadata:
    name: configmap
    namespace: default
    labels: 
        app: cm2
spec:
    containers:
    - name: cm2
      image: ikubernetes/myapp:v1
      ports: 
      - name: http
        containerPort: 80
      volumeMounts:
      - name: nginxconf
        mountPath: /etc/nginx/conf.d/
        readOnly: true
    volumes:
    - name: nginxconf
      configMap:
        name: nginx-www
